FROM maven:3.9-eclipse-temurin-17-alpine

WORKDIR /app

COPY spring-boot-backend/pom.xml ./
COPY spring-boot-backend/src ./src

RUN mvn clean package -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "target/demo-0.0.1-SNAPSHOT.jar"]